## data specific params
processed_tsv: "sample-info/hca-processed-libraries.tsv"
sce_dir: "results/human_cell_atlas/scpca-downstream-analyses"
results_dir: "results/human_cell_atlas"
pepfile: "sample-info/hca-project-pep.yaml"

# cell type information paramaters
add_celltype: true
celltype_file: "sample-info/hca-celltype-info.tsv"

# workflow paramters
seed: 2022
num_hvg: 5000
grouping_var: "project_name"

# for scvi only, what columns in the coldata should be used as covariates in integration
continuous_covariates: "subsets_mito_percent"
