---
params:
  group_name: "1M_Immune_Cells"
  merged_sce: "../results/human_cell_atlas/merged_sce/1M_Immune_Cells_merged_sce.rds"
  integrated_sce: "../results/human_cell_atlas/integrated_sce/1M_Immune_Cells_integrated_fastmnn_sce.rds"
  integration_method: "fastmnn"
  batch_column: "batch"
  celltype_column: "celltype"
  date: !r Sys.Date()

title: "`r glue::glue('Core analysis report for {params$library}')`"
author: "CCDL"
date: "`r params$date`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
    code_folding: hide
---

```{r}
library(SingleCellExperiment)
library(ggplot2)
theme_set(theme_bw())
```


```{r}
# load the R project
project_root <- here::here()
renv::load(project_root)

# source the helper functions to grab the integration method check 
source(file.path(project_root, "scripts", "utils", "integration-helpers.R"))

# check integration method and reassign
integration_method <- check_integration_method(params$integration_method)

# check for input files  
if(!file.exists(params$merged_sce)){
  stop("Merged SCE file provided does not exist")
}

if(!file.exists(params$integrated_sce)){
  stop("Integrated SCE file provided does not exist")
}

# read in sce objects 
merged_sce <- readr::read_rds(params$merged_sce)
integrated_sce <- readr::read_rds(params$integrated_sce)
```


```{r}
# read in sce objects 
merged_sce <- readr::read_rds(params$merged_sce)
integrated_sce <- readr::read_rds(params$integrated_sce)

# check that batch column is found in colData of both merged and integrated sce
coldata_names <- intersect(colnames(colData(merged_sce)), colnames(colData(integrated_sce)))
if(!params$batch_column %in% coldata_names){
  stop("Provided batch_column should be present in both the colData of the merged SCE and integrated SCE.")
}

if(!params$celltype_column %in% coldata_names){
  stop("Provided celltype_column should be present in both the colData of the merged SCE and integrated SCE.")
}

# grab dim reduction name to use for plotting 
integrated_umap_name <- paste0(integration_method, "_UMAP")

# check that UMAP is present in both SCE objects 
if(!"UMAP" %in% reducedDimNames(merged_sce)){
  stop("Missing UMAP embeddings from merged SCE object")
}

if(!integrated_umap_name %in% reducedDimNames(integrated_sce)){
  stop(glue::glue("Missing UMAP embeddings from integrated SCE object. 
       Make sure that UMAP embeddings are present and labeled with {integrated_umap_name}.")
  )
}
```

```{r fig.width=8, fig.height=8}
pre_integration_umap <- scater::plotReducedDim(merged_sce, 
                                               dimred = "UMAP",
                                               colour_by = params$batch_column) +
  theme(text = element_text(size = 16)) +
  ggtitle(paste(params$group_name, "Pre-Integration"))

post_integration_umap <- scater::plotReducedDim(integrated_sce,
                                                dimred = integrated_umap_name,
                                                colour_by = params$batch_column) +
  theme(text = element_text(size = 16)) +
  ggtitle(paste(params$group_name, "Post-Integration with", integration_method))

cowplot::plot_grid(pre_integration_umap,post_integration_umap, ncol = 1)
```

```{r}
pre_integration_umap <- scater::plotReducedDim(merged_sce, 
                                               dimred = "UMAP",
                                               colour_by = params$celltype_column) +
  ggtitle(paste(params$group_name, "Pre-Integration"))

post_integration_umap <- scater::plotReducedDim(integrated_sce,
                                                dimred = integrated_umap_name,
                                                colour_by = params$celltype_column) +
  ggtitle(paste(params$group_name, "Post-Integration with", integration_method))

cowplot::plot_grid(pre_integration_umap,post_integration_umap, ncol = 1)
```

