# Config file with relevant parameters updated for testing the
#  Snakefile pipeline with only one HCA dataset

processed_tsv: "sample-info/test/hca-processed-libraries.tsv"
pepfile: "sample-info/test/hca-project-pep.yaml"
celltype_file: "sample-info/test/hca-celltype-info.tsv"
