name: Test integration workflow

on:
  pull_request:
    branches:
      - main

jobs:
  test-snakemake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test snakemake
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: '.test'
          snakefile: 'Snakefile'
          args: '--list --configfile config.yaml'
          task: 'run'
